### ISSUE TITLE
Can not compile after update to latest Angular version 4.2.3

### ISSUE THREAD

**Issue by cevarief** [NativeScript/nativescript-angular#852]
Suddenly compilation failed after upgrade from angular 4.1.3 to 4.2.3.
 Go back to 4.1.3 works good. 
>
> 
> Support for Node.js 8.0.0 is not verified. This CLI might not install or run properly.
> 
> Executing before-prepare hook from /Users/cvr/project/hooks/before-prepare/nativescript-dev-sass.js
> Found peer node-sass
> Executing before-prepare hook from /Users/cvr/project/hooks/before-prepare/nativescript-dev-typescript.js
> Found peer TypeScript 2.3.4
> node_modules/nativescript-angular/router/page-router-outlet.d.ts(2,10): error TS2305: Module '/Users/cvr/project/node_modules/`@`angular/router/router' has no exported member 'RouterOutletMap'.
> 
> TypeScript compiler failed with exit code 1

**Comment by NathanWalker** [comment]
@cevarief support for 4.2 is coming in this PR:
https://github.com/NativeScript/nativescript-angular/pull/842
Perhaps close this issue?
