### ISSUE TITLE
A lot of TS2304 errors after upgrading nativescript to 3.0.1

### ISSUE THREAD

**Issue by rekotc** [NativeScript/nativescript-angular#865]
I've recently updated to nativescript 3.0.1 and i cant run my project anymore, i get a lot of errors like:

    node_modules/@angular/router/src/interfaces.d.ts error TS2304: Cannot find name "Promise"

I've googled the problem and i tried to update the module versions of my package.json, maybe i messed it up a bit, this is my current package.json:

  ```
"description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.myapp",
    "tns-ios": {
      "version": "2.5.0"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.0.1",
    "nativescript-telerik-ui": "^1.6.2",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^3.0.1",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.5",
    "typescript": "~2.3.4"
  }


```am i missing something? Thanks a lot.

**Comment by NickIliev** [comment]
@rekotc check your tsconfig.json content - it should look like[ this one](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/tsconfig.json)
