### ISSUE TITLE
TimePicker Two-Way Binding Error in 3.2.1

### ISSUE THREAD

**Issue by ShawnPavel** [NativeScript/nativescript-angular#1021]
Previously in Nativescript 2.x I used the timepicker by binding `ngModel` to a property in my `.ts` file. However after upgrading to 3.2.1 it seems that no longer works.

I created a clean project and was able to reproduce my issue by simply adding a `TimePicker` component to the default view and binding it like so:
```
<TimePicker [(ngModel)]="timeProp"></TimePicker>
```
The property in the `.ts` looks like this:
```
private time: Date = moment().toDate();
public get timeProp(): Date {
    return this.time;
}
public set timeProp(val: Date) {
    console.log(val.getHours() + ':' + val.getMinutes());
    this.time = val;
}
```
With this configuration the `console.log` never gets hit. However if I switch `ngModel` to `time` the binding works, but throws an error when the user changes the time:
```
JS: ERROR TypeError: newValue.getHours is not a function
JS: ERROR CONTEXT [object Object]
```
This error appears to be caused by the `val` object sent to the property setter. It isn't a `Date`, but is in fact the TimePicker control itself (the same object for the `timeChange` event).

**Comment by ShawnPavel** [comment]
It seems the DatePicker is the same way.

**Comment by NickIliev** [comment]
@ShawnPavel thank you for reporting this issue - it seems that this is a known bug and we are currently working on a fix. [The original issue is logged here ](https://github.com/NativeScript/nativescript-angular/issues/963)and you can keep an eye on it for updates.

Meanwhile, as a workaround, you can try [this approach](https://github.com/NativeScript/nativescript-angular/issues/963#issuecomment-325584072)

Closing as duplicate to [https://github.com/NativeScript/nativescript-angular/issues/963](https://github.com/NativeScript/nativescript-angular/issues/963)
